name: simple_gui
description: A new Flutter project.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^2.4.8
  intl: ^0.19.0
  ionicons: ^0.2.2
  material_design_icons_flutter: ^7.0.7296
  path: ^1.8.3
  path_provider: ^2.1.1
  shared_preferences: ^2.3.1
  url_launcher: ^6.1.13
  uuid: ^4.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: "Iansui"
      fonts:
        - asset: assets/fonts/Iansui.ttf
  assets:
    - assets/window_system/
    - assets/vaccine_timeline/
    - assets/vaccine_timeline/images/
    - assets/desktop/icons/
    - assets/avatars/
